import pyautogui
pyautogui.FAILSAFE = False
from win32api import GetSystemMetrics
import os
print("SalesMate + Backup Manu Test")

path="C:/SMP"
if not os.path.exists(path):
    os.makedirs(path)
width= GetSystemMetrics(0)
height=GetSystemMetrics(1)
print("click on the botton left to launch the start menu")
pyautogui.click(0,height) 
print("Select the SalesMate + Application")
pyautogui.typewrite("SalesMate +")
print("Press Enter Key to Launch SalesMate + Application and Wait for 10 Sec")
pyautogui.press("enter",2,8)
print("Press Enter Key again to close the Tip Of the Day Dialog")
pyautogui.press("enter")
print("Now alt and f shortcut key in  Salesmate to invoke the File Root menu")
pyautogui.press(['alt','f'])
print("Now press 'b' to invoke the Backup Folder Dialog")
pyautogui.press("b")
print("Go to C Drive")
pyautogui.press("l",1,1)
print("Now press Right arrow Key to Expand the Tree")
pyautogui.press("right",1,1)
print("Go to SMP Folder")
pyautogui.typewrite("smp")
pyautogui.press("enter",1,1)
print("Press Enter Again to Close the OK Button")
pyautogui.press("enter")
print("Press  alt and e shortcut key in Salemate to invoke the Setup Root menu")
pyautogui.press(['alt','e'])
print("Now press 'v' to invoke the Service Master")
pyautogui.press("v",1,1)
print("Now press 'n' to select New from Service Details")
pyautogui.press("n")
pyautogui.press("enter",1,1)
print("Print Service Name")
pyautogui.typewrite("Dinner Party")
pyautogui.press("enter",1,1)
print("Print Description")
pyautogui.typewrite("1000 Persons")
pyautogui.press("enter",1,1)
print("Print Standard Rate")
pyautogui.typewrite("200")
pyautogui.press("enter",3,2)
pyautogui.press("c",1,2)
print("Press  alt and c shortcut key in Salemate to invoke the Customer Root menu ")
pyautogui.press(['alt','c'])
print("Now press 'a' to invoke the Add Customer")
pyautogui.press("a")
pyautogui.press("enter",2,1)
print("Enter First Name")
pyautogui.typewrite("Rama")
pyautogui.press("enter",1,1)
print("Enter Second Name")
pyautogui.typewrite("Chandran")
pyautogui.press("enter",1,1)
print("Enter Title")
pyautogui.typewrite("Mr")
pyautogui.press("enter",1,1)
print("Enter Address")
pyautogui.typewrite("Flat No.23")
pyautogui.press("enter",1,1)
print("Enter Phone No")
pyautogui.typewrite("9785421685")
pyautogui.press("enter",1,1)
print("Enter Email ID")
pyautogui.typewrite("ramachandran@gmail.com")
pyautogui.press("enter",4,1)
print("Now press 'a' to save")
pyautogui.press("a",1,1)
pyautogui.press("enter",1,1)
